# from https://raw.githubusercontent.com/tomsik68/docker-xampp/master/Dockerfile
FROM ghcr.io/tna76874/schoolnotebookjava:stable-2023110509

ENV DEBIAN_FRONTEND noninteractive

USER root

RUN usermod --password $(echo "root" | openssl passwd -1 -stdin) root

RUN apt-get update --fix-missing && \
  apt-get install -y --no-install-recommends curl net-tools openssh-server \
      supervisor nano vim less inotify-tools && \
  rm -rf /var/lib/apt/lists/*

RUN curl -Lo xampp-linux-installer.run "https://sourceforge.net/projects/xampp/files/XAMPP%20Linux/8.2.12/xampp-linux-x64-8.2.12-0-installer.run/download"

RUN chmod +x xampp-linux-installer.run && \
  bash -c './xampp-linux-installer.run' && \
  # Delete the installer after it's done to make the resulting image smaller
  rm xampp-linux-installer.run && \
  ln -sf /opt/lampp/lampp /usr/bin/lampp && \
  # Enable XAMPP web interface(remove security checks)
  sed -i.bak s'/Require local/Require all granted/g' /opt/lampp/etc/extra/httpd-xampp.conf && \
  # Enable error display in php
  sed -i.bak s'/display_errors=Off/display_errors=On/g' /opt/lampp/etc/php.ini && \
  # Enable includes of several configuration files
  mkdir /opt/lampp/apache2/conf.d && \
  echo "IncludeOptional /opt/lampp/apache2/conf.d/*.conf" >> /opt/lampp/etc/httpd.conf && \
  # Create a /www folder and a symbolic link to it in /opt/lampp/htdocs. It'll be accessible via http://localhost:[port]/www/
  # This is convenient because it doesn't interfere with xampp, phpmyadmin or other tools in /opt/lampp/htdocs
  mkdir /www && \
  ln -s /www /opt/lampp/htdocs && \
  # SSH server
  mkdir -p /var/run/sshd && \
  # Allow root login via password
  sed -ri 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/g' /etc/ssh/sshd_config

COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

VOLUME [ "/var/log/mysql/", "/var/log/apache2/", "/www", "/opt/lampp/apache2/conf.d/" ]

EXPOSE 8888
EXPOSE 3306
EXPOSE 22
EXPOSE 80

CMD ["/usr/bin/supervisord", "-n"]